FROM python:3.12-slim
WORKDIR /srv
# Generated by scripts/setup.sh; deliberately require a reviewed dependency lock.
COPY requirements.lock .
RUN pip install --no-cache-dir -r requirements.lock
COPY copilot ./copilot
COPY runbooks ./runbooks
COPY app ./app
RUN useradd --uid 10001 --create-home demo && mkdir /data && chown demo /data
ENV PORT=8080 BUDGET_DB=/data/demo.sqlite3
EXPOSE 8080
ENTRYPOINT ["python", "app/container_entrypoint.py"]
CMD ["sh", "-c", "exec uvicorn app.main:app --workers 1 --host 0.0.0.0 --port ${PORT}"]
