"""Pin the installed, tested dependency closure without network access.

Evaluate markers for both local macOS and Linux Python 3.12. This generates
version locks, not wheel hashes. Missing platform dependencies fail explicitly.
"""
from importlib.metadata import distribution
from pathlib import Path
from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parent.parent


def roots(path):
    out = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if line.startswith("-r "):
            out.extend(roots(path.parent/line[3:]))
        elif line and not line.startswith("#"):
            out.append(Requirement(line))
    return out


def lock(source, destination):
    queue = [(r, None) for r in roots(ROOT/source)]
    seen = set()
    versions = {}
    environments = []
    for system, platform_name in (("Darwin", "darwin"), ("Linux", "linux")):
        env = default_environment()
        env.update(platform_system=system, sys_platform=platform_name, os_name="posix",
                   python_version="3.12", implementation_name="cpython")
        environments.append(env)
    while queue:
        req, parent_extras = queue.pop()
        if req.marker and not any(req.marker.evaluate({**env, "extra": extra})
                                  for env in environments for extra in (parent_extras or {""})):
            continue
        name = canonicalize_name(req.name)
        dist = distribution(name)
        if req.specifier and not req.specifier.contains(dist.version, prereleases=True):
            raise ValueError(f"Installed {name}=={dist.version} does not satisfy {req}")
        versions[name] = dist.version
        key = (name, tuple(sorted(req.extras)))
        if key in seen:
            continue
        seen.add(key)
        queue.extend((Requirement(child), req.extras | {""}) for child in dist.requires or [])
    header = "# Installed/tested Python 3.12 version pins; generated by scripts/lock_environment.py.\n# Supports macOS and Linux markers. Wheel hashes are not included.\n"
    (ROOT/destination).write_text(header+"\n".join(f"{name}=={version}" for name, version in sorted(versions.items()))+"\n")
    print(f"{destination}: {len(versions)} pinned packages")


if __name__ == "__main__":
    lock("requirements.txt", "requirements.lock")
    lock("requirements-dev.txt", "requirements-dev.lock")
